### PR TITLE
Unautz action expr parsing

### PR DESCRIPTION
**Pull request by ryanwilliamnicholls**
I've raised this because I've had issues at my work with two different scenarios. Some old legacy systems had need for processing unauthenticated users within an iframe and users with specific versions of safari were failing the default check due to compatibility issues with sec-fetch headers. 

I've added the custom expression parsing that already exists on `OIDCUnAuthAction` to `OIDCUnAutzAction` when the action is `auth`. The expression overrides the default but behaves in the same way, if the expression passes then the user can be redirected to the OpenID Connect Provider. If the expression fails it behaves the same way that the existing default expression check fails.

### CODE REVIEW

**Comment by zandbelt** [comment]
I'm not sure this is needed: what exactly were the problems you were encountering and what did your config look like?

**Comment by ryanwilliamnicholls** [comment]
The issue that initially caused me to raise this was with a standard config and `OIDCUnAutzAction auth`, certain setups, such as within an iframe, and more recently certain versions of safari that don't support `Sec-Fetch-Mode` or `Sec-Fetch-Dest` always fails because the following code always will return FALSE:

```
apr_byte_t oidc_is_auth_capable_request(request_rec *r) {

	if ((oidc_http_hdr_in_x_requested_with_get(r) != NULL) &&
	    (_oidc_strnatcasecmp(oidc_http_hdr_in_x_requested_with_get(r), OIDC_HTTP_HDR_VAL_XML_HTTP_REQUEST) == 0))
		return FALSE;

	if ((oidc_http_hdr_in_sec_fetch_mode_get(r) != NULL) &&
	    (_oidc_strnatcasecmp(oidc_http_hdr_in_sec_fetch_mode_get(r), OIDC_HTTP_HDR_VAL_NAVIGATE) != 0))
		return FALSE;

	if ((oidc_http_hdr_in_sec_fetch_dest_get(r) != NULL) &&
	    (_oidc_strnatcasecmp(oidc_http_hdr_in_sec_fetch_dest_get(r), OIDC_HTTP_HDR_VAL_DOCUMENT) != 0))
		return FALSE;

	if ((oidc_http_hdr_in_accept_contains(r, OIDC_HTTP_CONTENT_TYPE_TEXT_HTML) == FALSE) &&
	    (oidc_http_hdr_in_accept_contains(r, OIDC_HTTP_CONTENT_TYPE_APP_XHTML_XML) == FALSE) &&
	    (oidc_http_hdr_in_accept_contains(r, OIDC_HTTP_CONTENT_TYPE_ANY) == FALSE))
		return FALSE;

	return TRUE;
}

`````

In the case of `OIDCUnAuthAction` this can be overridden, but there's no way to override this in `OIDCUnAutzAction`.

**Comment by zandbelt** [comment]
what does your config look like?

**Comment by ryanwilliamnicholls** [comment]
Here is the config.

```
OIDCProviderMetadataURL https://accounts.xxxx/.well-known/openid-configuration
OIDCClientID xxxxxxx
OIDCClientSecret xxxxxx
OIDCResponseType code
OIDCProviderIssuer https://accounts.xxxx
OIDCRedirectURI https://xxxx/protected/redirect
OIDCCryptoPassphrase xxxxxxxx
OIDCScope "openid confirm-access"
OIDCUserInfoRefreshInterval 60 logout_on_error


<Location "/">
    <RequireAll>
       Require valid-user
       Require claim "suspended:false"
    </RequireAll>
    AuthType openid-connect
    OIDCPathAuthRequestParams "prompt=login&login_hint=#"
    OIDCUnAuthAction 401 "%{HTTP:X-Requested-With} == 'XMLHttpRequest' \
                 || ( -n %{HTTP:Sec-Fetch-Mode} && %{HTTP:Sec-Fetch-Mode} != 'navigate' ) \
                 || ( -n %{HTTP:Sec-Fetch-Dest} && %{HTTP:Sec-Fetch-Dest} != 'iframe' && %{HTTP:Sec-Fetch-Dest} != 'frame' && %{HTTP:Sec-Fetch-Dest} != 'document') \
                 || (    ( %{HTTP_ACCEPT} !~ m#text/html# ) \
                      && ( %{HTTP_ACCEPT} !~ m#application/xhtml\+xml# ) \
                      && ( %{HTTP_ACCEPT} !~ m#\*/\*# ) )"
    OIDCUnAutzAction 302 auth-error.htm
</Location>

<LocationMatch "/urlThatReuiresStepUp/"> 
    <RequireAll>
       Require valid-user
       Require claim "restricted:true"
       Require claim "suspended:false"
    </RequireAll>
    AuthType openid-connect
    OIDCUnAutzAction auth #Does not work
    OIDCPathScope "restricted-access"
    OIDCPathAuthRequestParams prompt=login&acr_values=restricted-rechallenge
</LocationMatch>
```

The OIDCUnAutzAction auth does not work in the iframes in some of the legacy systems and on some versions of safari that we needed to support for our users.
I've been running the modified code in this pull request in a custom binary so our actual config looks closer to:

```
    OIDCUnAutzAction auth "%{HTTP:X-Requested-With} != 'XMLHttpRequest' \
            && (( -n %{HTTP:Sec-Fetch-Mode} && %{HTTP:Sec-Fetch-Mode} == 'navigate' ) \
            && ( -n %{HTTP:Sec-Fetch-Dest} && (%{HTTP:Sec-Fetch-Dest} == 'iframe' || %{HTTP:Sec-Fetch-Dest} == 'frame' || %{HTTP:Sec-Fetch-Dest} == 'document'))  || ( %{HTTP_USER_AGENT} =~ m#Mac OS X# ))\
            && (    ( %{HTTP_ACCEPT} =~ m#text/html# ) \
            || ( %{HTTP_ACCEPT} =~ m#application/xhtml\+xml# ) \
            || ( %{HTTP_ACCEPT} =~ m#\*/\*# ) )"
```

**Comment by zandbelt** [comment]
doing step up authentication in an iframe is something that should be avoided because of clickjacking attacks

**Comment by ryanwilliamnicholls** [comment]
Outside of the iframe issue, there's still the issue of a wide range of safari versions that cannot perform step up authentication at all because they don't support the sec-fetch headers that the default check expects.

**Comment by zandbelt** [comment]
wouldn't the following be more concise:
```c
diff --git a/src/handle/authz.c b/src/handle/authz.c
index 1610fd5..a7975ce 100644
--- a/src/handle/authz.c
+++ b/src/handle/authz.c
@@ -495,8 +495,12 @@
 		 * complete an authentication round trip to the provider, we
 		 * won't redirect the user and thus avoid creating a state cookie
 		 */
-		if (oidc_is_auth_capable_request(r) == FALSE) {
-			OIDC_METRICS_COUNTER_INC(r, c, OM_AUTHZ_ACTION_401);
+		if (oidc_dir_cfg_unauth_expr_is_set(r) == FALSE) {
+			if (oidc_is_auth_capable_request(r) == FALSE) {
+				OIDC_METRICS_COUNTER_INC(r, c, OM_AUTHZ_ACTION_401);
+				return AUTHZ_DENIED;
+			}
+		} else if (oidc_dir_cfg_unauth_action(r) != OIDC_UNAUTH_AUTHENTICATE) {
 			return AUTHZ_DENIED;
 		}
 
```

**Comment by ryanwilliamnicholls** [comment]
Yeah actually, didn't think of that, that would work.

**Comment by zandbelt** [comment]
please try/confirm 0aa5431d917a635f77e473fdb725f4438c561b74

**Comment by ryanwilliamnicholls** [comment]
Hi, sorry about the delay testing this.

There appears to be an issue with line 

`if (oidc_cfg_dir_unauth_action_get(r) != OIDC_UNAUTH_AUTHENTICATE) {`

Because the behavior of OIDCUnauthAction is to override auth with the argument 2, if the expression matches:
```
# E.g to only return 401 for cURL based user agents and "auth" for any other browsers/user agents:
#   OIDCUnAuthAction 401 "%{HTTP_USER_AGENT} =~ /curl/"
```

In a case where this OIDCUnAuthAction from the examples is set, the ```oidc_cfg_dir_unauth_action_get``` will return `OIDC_UNAUTH_RETURN401` and wont check the expression.

**Comment by zandbelt** [comment]
I don't follow: the idea is that if you want to return "auth" in the authorization phase for a particular client, you'd also want to do that in the authentication phase. So the expression you mentioned returns 401 only for CURL clients, all other clients should be redirected for authentication, which I think is the goal here. `oidc_cfg_dir_unauth_action_get` will actually interpret the expression and return OIDC_UNAUTH_AUTHENTICATE for non-curl clients. If you have a test config that doesn't work like that, please paste it here.

**Comment by ryanwilliamnicholls** [comment]
Sorry about that, i had an error in my config that made it appear like it wasn't working due to a code issue, my mistake. 
I've retested it again with a fresh config and its working as expected.

**Pull request closed without merging**
